#!/bin/bash
./build/gzip_parser data/validata/linear_elasticity_simple_prec_results.dat.gz data/validata-copy/linear_elasticity_simple_prec_results.dat
./build/gzip_parser data/validata/multi_poisson_simple_prec_results.dat.gz data/validata-copy/multi_poisson_simple_prec_results.dat
./build/gzip_parser data/validata/multi_poisson_two_plus_three_prec_results.dat.gz data/validata-copy/multi_poisson_two_plus_three_prec_results.dat
./build/gzip_parser data/validata/multi_poisson_two_plus_three_upper_triangular_prec_results.dat.gz data/validata-copy/multi_poisson_two_plus_three_upper_triangular_prec_results.dat
./build/gzip_parser data/validata/multi_poisson_two_plus_three_upper_triangular_with_sub_prec_results.dat.gz data/validata-copy/multi_poisson_two_plus_three_upper_triangular_with_sub_prec_results.dat
./build/gzip_parser data/validata/multi_poisson_two_plus_three_upper_triangular_with_two_sub_prec_results.dat.gz data/validata-copy/multi_poisson_two_plus_three_upper_triangular_with_two_sub_prec_results.dat
./build/gzip_parser data/validata/multi_poisson_two_plus_three_upper_triangular_with_replace_prec_results.dat.gz data/validata-copy/multi_poisson_two_plus_three_upper_triangular_with_replace_prec_results.dat
./build/gzip_parser data/validata/multi_poisson_coarse_two_plus_two_plus_one_prec_results.dat.gz data/validata-copy/multi_poisson_coarse_two_plus_two_plus_one_prec_results.dat
./build/gzip_parser data/validata/multi_poisson_one_plus_four_with_two_coarse_results.dat.gz data/validata-copy/multi_poisson_one_plus_four_with_two_coarse_results.dat
./build/gzip_parser data/validata/multi_poisson_upper_triangular_prec_results.dat.gz data/validata-copy/multi_poisson_upper_triangular_prec_results.dat
./build/gzip_parser data/validata/driven_cavity_results.dat.gz data/validata-copy/driven_cavity_results.dat
./build/gzip_parser data/validata/DenseLU_results.dat.gz data/validata-copy/DenseLU_results.dat
./build/gzip_parser data/validata/results_Pe200.dat.gz data/validata-copy/results_Pe200.dat
./build/gzip_parser data/validata/SuperLU_solve_error.dat.gz data/validata-copy/SuperLU_solve_error.dat
./build/gzip_parser data/validata/results_Pe200.dat.gz data/validata-copy/results_Pe200.dat
./build/gzip_parser data/validata/GMRES_solve_error.dat.gz data/validata-copy/GMRES_solve_error.dat
./build/gzip_parser data/validata/results_Pe200.dat.gz data/validata-copy/results_Pe200.dat
./build/gzip_parser data/validata/BiCGStab_solve_error.dat.gz data/validata-copy/BiCGStab_solve_error.dat
./build/gzip_parser data/validata/results_Pe0.dat.gz data/validata-copy/results_Pe0.dat
./build/gzip_parser data/validata/CG_solve_error.dat.gz data/validata-copy/CG_solve_error.dat
./build/gzip_parser data/validata/results_Pe0.dat.gz data/validata-copy/results_Pe0.dat
./build/gzip_parser data/validata/GS_solve_error.dat.gz data/validata-copy/GS_solve_error.dat
./build/gzip_parser data/validata/results_Pe0.dat.gz data/validata-copy/results_Pe0.dat
./build/gzip_parser data/validata/DampedJacobi_solve_error.dat.gz data/validata-copy/DampedJacobi_solve_error.dat
./build/gzip_parser data/validata/direct_solver_matrix_solve_result.dat.gz data/validata-copy/direct_solver_matrix_solve_result.dat
./build/gzip_parser data/validata/direct_solver_problem_solve_result.dat.gz data/validata-copy/direct_solver_problem_solve_result.dat
./build/gzip_parser data/validata/direct_solver_problem_solve_result.dat.gz data/validata-copy/direct_solver_problem_solve_result.dat
./build/gzip_parser data/validata/direct_solver_matrix_solve_result.dat.gz data/validata-copy/direct_solver_matrix_solve_result.dat
./build/gzip_parser data/validata/direct_solver_matrix_solve_result.dat.gz data/validata-copy/direct_solver_matrix_solve_result.dat
./build/gzip_parser data/validata/direct_solver_problem_solve_result.dat.gz data/validata-copy/direct_solver_problem_solve_result.dat
